#!/bin/bash

# echo "sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list' "

export PATH=$PATH:/home


sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654

sudo apt-get update
sudo apt-get -y install ros-kinetic-desktop-full
sudo rosdep init
rosdep update
echo "source /opt/ros/kinetic/setup.bash" >> ~/.bashrc
source ~/.bashrc
sudo apt -y install python-rosinstall python-rosinstall-generator python-wstool build-essential
sudo apt-get -y install build-essential
sudo apt-get -y install cmake


# Create a workspace
mkdir ros_to_rtsp_ws
cd ros_to_rtsp_ws
mkdir src
catkin_make
cd src
git clone "https://github.com/CircusMonkey/ros_rtsp.git"
cd ..
catkin_make

# Install Gstreamer and it's packages needed
sudo apt -y install git autoconf autopoint libtool bison flex gtk-doc-tools
sudo apt -y install libglib2.0-dev freeglut3 freeglut3-dev yasm libreadline-dev
sudo apt -y install libgvc6 graphviz-dev # for GstShark
sudo apt-get -y install libgstreamer-plugins-base1.0-dev libgstreamer-plugins-good1.0-dev libgstreamer-plugins-bad1.0-dev libgstrtspserver-1.0-dev 

# Install VLC
sudo apt-get install vlc

# Dependencies again....Not even sure what they are
sudo apt-get -y install build-essential
sudo apt-get -y  install bison
sudo apt-get -y install flex
sudo apt-get -y install libglib2.0-dev
